[build]
  command = "npm run build"
  publish = "dist"

[context.production.environment]
  VITE_API_URL = "https://meta-insights-api.onrender.com/api"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200