services:
  - type: web
    name: meta-insights-api
    env: node
    region: europe-west2
    buildCommand: npm install
    startCommand: node server/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: DB_NAME
        value: NewVici
      - key: DB_USER
        value: dal
      - key: DB_PASSWORD
        value: samson01
      - key: INSTANCE_UNIX_SOCKET
        value: /cloudsql/meta-insights-414802:us-central1:meta-insights
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 24h
      - key: META_ACCESS_TOKEN
        sync: false
      - key: FRONTEND_URL
        value: https://tourmaline-pie-2188b7.netlify.app
    healthCheckPath: /health
    autoDeploy: true