services:
  - type: web
    name: meta-insights-api
    env: node
    region: frankfurt
    buildCommand: npm install
    startCommand: node server/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: DATABASE_URL
        fromDatabase:
          name: meta_insights_db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 24h
      - key: META_APP_ID
        sync: false
      - key: META_APP_SECRET
        sync: false
      - key: META_API_VERSION
        value: v18.0
      - key: CORS_ALLOWED_ORIGINS
        value: https://tourmaline-pie-2188b7.netlify.app
      - key: FRONTEND_URL
        value: https://tourmaline-pie-2188b7.netlify.app

databases:
  - name: meta_insights_db
    region: frankfurt
    plan: free